services:
    planner-app:
        user: "${UID:-1000}:${GID:-1000}"
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: planner-app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - composer_cache:/root/.composer/cache
        depends_on:
            db:
                condition: service_healthy
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: planner-nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - planner-app
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: planner-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
        networks:
            - laravel
        healthcheck:
            test: ["CMD-SHELL", "mysql -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"]
            interval: 5s
            timeout: 5s
            retries: 10

volumes:
    dbdata:
    composer_cache:

networks:
    laravel:
