services:
    planner-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: planner-app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        networks:
            - laravel
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mysql:8.0
        container_name: planner-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test: ["CMD-SHELL", "mysql -h 127.0.0.1 -u laravel -psecret -e 'SELECT 1;'"]
            interval: 5s
            timeout: 5s
            retries: 10

    web:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - planner-app
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
